ALTER TABLE PORTALRH.T_MENU ADD ID_INCLUIR NUMBER(1,0) DEFAULT 0;
ALTER TABLE PORTALRH.T_MENU ADD ID_EXCLUIR NUMBER(1,0) DEFAULT 0;
ALTER TABLE PORTALRH.T_MENU ADD ID_ALTERAR NUMBER(1,0) DEFAULT 0;
ALTER TABLE PORTALRH.T_PERFIL_MENU ADD ID_INCLUIR NUMBER(1,0) DEFAULT 0;
ALTER TABLE PORTALRH.T_PERFIL_MENU ADD ID_EXCLUIR NUMBER(1,0) DEFAULT 0;
ALTER TABLE PORTALRH.T_PERFIL_MENU ADD ID_ALTERAR NUMBER(1,0) DEFAULT 0;
